//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class AIController : MonoBehaviour {

	public float cooldown = 1f;
	public float accuracy = 10f;

	protected IShip ship;
	protected Transform target;

	float timer;


	protected virtual void Start() {
		ship = GetComponent<IShip>();
		Debug.Log (ship);
		target = GameObject.FindGameObjectWithTag("Player").transform;
		Debug.Log(target);
	}

	protected virtual void Update() {
		timer = Mathf.Max (0f, timer - Time.deltaTime);
	}

	protected bool Fire() {
		return ship.Fire ();
	}

}

