//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class AIControllerCircle : MonoBehaviour {

	public float Radius;
	public float Velocity;

	IShip ship;

	void Awake() {
		ship = GetComponent<IShip>();
		ship.SetInitialPosition(new Vector3(-Radius,0f,0f));
		ship.SetInitialVelocity(new Vector3(0f,Velocity,0f));
		ship.SetInitialAcceleration(new Vector3(Velocity*Velocity/Radius, 0f, 0f));
	}

	void Update() {
		ship.Accelerate(getAcceleration());
	}

	Vector3 getAcceleration() {
		float magnitude = Velocity*Velocity/Radius;
		Vector3 direction = -transform.position.normalized;
		Debug.Log (magnitude*direction);
		return magnitude*direction;
	}

}

