//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


public class AIControllerStraight : AIController {

	override
	protected void Update() {
		base.Update ();
		Debug.Log(ship);
		Debug.Log(ship.weapon);
		ship.weapon.Face (target, accuracy);
		Fire ();
	}

	override protected void SetModifiers(int level) {

	}

}

