//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AIControllerZigzag : AIController {

	public float amplitude = 3;

	IShip ship;

	void Start() {
		ship = GetComponent<IShip>();
		ship.rigidbody.AddForce(Vector3.right*amplitude, ForceMode.VelocityChange);
	}

	void Update() {
		ship.Accelerate(getAcceleration());
	}

	Vector3 getAcceleration() {
		return -transform.position.x*Vector3.right;
	}

}

