//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class AIControllerBoss : AIController {

	override protected void Update() {
		Vector3 newVelocity = getNewVelocity();
		ship.rigidbody.velocity = newVelocity;
		ship.weapon.Face (target, 50f);
		ship.Fire();
	}

	override protected void SetModifiers(int level) {

	}

	Vector3 getNewVelocity() {
		Vector3 v = new Vector3(target.position.x - transform.position.x, target.position.y - transform.position.y, 0f);
		return Vector3.Lerp (rigidbody.velocity, v, Time.deltaTime);
	}

}

