//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class IWeapon : MonoBehaviour {

	public Transform shootPosition;

	public abstract GameObject Fire();

	public void Face(Transform target, float accuracy) {
//		Debug.Log (target);
//		Debug.Log (shootPosition);
		if (target == null) {
			return;
		}
		if (Vector3.Angle(transform.up, target.position - transform.position) > 90f) {
			shootPosition.rotation = transform.rotation;
			return;
		}
		Quaternion newRotation = Quaternion.LookRotation (target.position-shootPosition.position);
		shootPosition.transform.rotation = Quaternion.Lerp (transform.rotation, newRotation, accuracy);
	}

}

