//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class WeaponAdapter : IWeapon {

	public BasicWeapon basicWeapon;
	public Transform shootPosition;
	public float cooldown;

	float cooldownRemaining;
	bool canFire;

	void Start() {
		basicWeapon.speed = 20f;
		basicWeapon.initProjectile (20, BasicProjectile.projectileType.bullet);
		cooldownRemaining = 0f;
		canFire = true;
	}

	void Update() {
		cooldownRemaining = Mathf.Max (0f, cooldownRemaining-Time.deltaTime);
		if (cooldownRemaining == 0f) {
			canFire = true;
		}
	}

	override
	public bool Fire() {
		if (canFire) {
			cooldownRemaining = cooldown;
			canFire = false;
			basicWeapon.shootProjectiles (shootPosition.position, shootPosition.rotation, basicWeapon.projectile.rigidbody);
			return true;
		}
		else {
			return false;
		}
	}

}

